version: "3.8"

services:
    openapi-to-mcpserver:
        image: openapi-to-mcpserver:latest
        container_name: openapi-to-mcpserver
        restart: unless-stopped
        ports:
            - "8080:8080"
        environment:
            - TZ=Asia/Shanghai
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--spider",
                    "-q",
                    "http://localhost:8080/health",
                ]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 5s
